RealStoriesExposed/Areas/Administration/Controllers/StoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using RealStoriesExposed.Models;
using RealStoriesExposed.Areas.Administration.ViewModels;
using RealStoriesExposed.Controllers;
using RealStoriesExposed.Common;
using Microsoft.AspNet.Identity;
using RealStoriesExposed.Data;
using RealStoriesExposed.Services.Contracts;

namespace RealStoriesExposed.Areas.Administration.Controllers
{
    public class StoriesController : BaseController
    {
    
        private SelectList _accessibleUsers;
        private List<Story> _accessibleStories;

        private IStoriesService StoriesService;
        private IUsersService UsersService;
        private SelectList AccessibleUsers {
            get {
                return _accessibleUsers ?? new SelectList(UsersService.GetAccessibleUsers(User.Identity.GetUserId()), "Id", "Email");
            }
            set { _accessibleUsers = value; }
        }

        
        public List<Story> AccessibleStories {
            get {
                return _accessibleStories ?? StoriesService.GetAccessibleStories(User.Identity.GetUserId()).ToList();
            }
            set { _accessibleStories = value; }
        }

        public StoriesController(IStoriesService _storiesService, IUsersService usersService)
        {
            this.StoriesService = _storiesService;
            this.UsersService = usersService;
        }
        
        [Authorize]
        // GET: Administration/Stories
        public ActionResult Index()
        {
            var stories = Mapper.Map<List<Story>, List<StoryViewModel>>(AccessibleStories);
            
            return View(stories);
        }

        [Authorize]
        // GET: Administration/Stories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Story story = StoriesService.Find(id);
            if (story == null)
            {
                return HttpNotFound();
            }
            return View(story);
        }


        [Authorize]
        // GET: Administration/Stories/Create
        public ActionResult Create()
        {
            var storyVM = new StoryViewModel();

            storyVM.Users = AccessibleUsers;       

            return View(storyVM); 
        }

        // POST: Administration/Stories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StoryViewModel storyVM)
        {
            storyVM.Users = AccessibleUsers;

            if (ModelState.IsValid)
            {
                var dbStory = Mapper.Map<Story>(storyVM);
                StoriesService.Add(dbStory);
                return RedirectToAction("Index");
            }

            return View(storyVM);
        }

        [Authorize]
        // GET: Administration/Stories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var story = StoriesService.Find(id);
            StoryViewModel storyVM = Mapper.Map<StoryViewModel>(story); 
           
            if (story == null)
            {
                return HttpNotFound();
            }

            storyVM.Users = AccessibleUsers;

            return View(storyVM);
        }

        // POST: Administration/Stories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(StoryViewModel storyVM)
        {
            storyVM.Users = AccessibleUsers;
                       
            if (ModelState.IsValid)
            {
                var story = Mapper.Map<Story>(storyVM);
                StoriesService.Update(story);
                StoriesService.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(storyVM);
        }

        [Authorize]
        // GET: Administration/Stories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Story story = StoriesService.Find(id);
            if (story == null)
            {
                return HttpNotFound();
            }
            return View(story);
        }

        // POST: Administration/Stories/Delete/5
        [HttpPost, ActionName("Delete")] 
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Story story = StoriesService.Find(id);
            StoriesService.Delete(story);
            return RedirectToAction("Index");
        } 

        //protected override void Dispose(bool disposing)
        //{ 
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

RealStoriesExposed/Views/Shared/_Layout.cshtml
@{
    ViewBag.Title = "Real Stories Exposed";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                
                @if (Request.IsAuthenticated)
                {
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink(User.Identity.Name, "Index", "Manage", null, new { @class = "btn custom-btn navbar-btn " })</li>
                            <li>@Html.ActionLink("My Stories", "index", "Stories", new { Area = "Administration" }, new { @class = "btn custom-btn navbar-btn" })</li>
                            <li>@Html.ActionLink("New Story", "Create", "Stories", new { Area = "Administration" }, new { @class = "btn custom-btn navbar-btn" })</li>
                            <li>@Html.ActionLink("Log out", "LogOff", "Account", null, new { @class = "btn custom-btn navbar-btn" })</li>
                        </ul>
                    </div>
                }
                else
                {
                    @Html.ActionLink("Log In", "Login", "Account", null, new { @class = "btn btn-info custom-btn navbar-btn" })
                    @Html.ActionLink("Register", "Register", "Account", null, new { @class = "btn btn-success custom-btn navbar-btn" })                    
                }
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @Html.ActionLink("Home", "Index", "Home", null, new { @class = "btn custom-btn navbar-btn" })
                    </li>
                    <li>
                        @Html.ActionLink("About", "About", "Home", null, new { @class = "btn custom-btn navbar-btn" })
                    </li>
                    <li>
                        @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "btn custom-btn navbar-btn" })
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1><span>Real Stories Exposed</span></h1>
                        <hr class="small">
                        <span class="subheading">The spicey place for life experience</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                @RenderBody()                 
            </div>
        </div>
    </div>
    <hr>
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>



@*<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>*@